# attention module golden model

In [4]:
from golden_model import AttentionModule

In [9]:
embed_dim = 4
seq_length = 8

query = torch.rand(seq_length, embed_dim)
key = torch.rand(seq_length, embed_dim)
value = torch.rand(seq_length, embed_dim)

atten_compute = AttentionModule()

attn_output, attn_weights = atten_compute.Attention(query, key, value)

print(query)
print(key)
print(value)


print( attn_output )
print( attn_weights)


tensor([[0.6967, 0.3495, 0.6867, 0.9485],
        [0.1650, 0.2222, 0.9522, 0.8134],
        [0.9100, 0.5385, 0.3823, 0.8618],
        [0.9457, 0.9979, 0.8915, 0.4255],
        [0.0727, 0.8653, 0.6557, 0.4207],
        [0.5359, 0.7937, 0.9122, 0.1057],
        [0.3248, 0.0791, 0.8580, 0.9853],
        [0.7351, 0.6106, 0.2567, 0.1358]])
tensor([[0.7527, 0.0226, 0.4261, 0.0482],
        [0.1117, 0.6792, 0.8845, 0.1269],
        [0.3165, 0.9162, 0.2062, 0.0437],
        [0.2115, 0.2096, 0.9432, 0.3832],
        [0.3239, 0.8577, 0.2060, 0.2139],
        [0.7957, 0.9314, 0.9457, 0.6553],
        [0.1274, 0.8892, 0.7027, 0.1668],
        [0.0715, 0.6881, 0.5510, 0.0402]])
tensor([[0.9066, 0.3466, 0.5183, 0.2468],
        [0.7190, 0.9354, 0.7528, 0.3610],
        [0.6260, 0.9892, 0.6463, 0.5128],
        [0.5988, 0.4278, 0.2862, 0.2730],
        [0.8817, 0.9981, 0.9600, 0.7173],
        [0.8447, 0.5732, 0.4521, 0.1180],
        [0.2706, 0.5099, 0.6242, 0.8518],
        [0.6449, 0.4259, 0.0524,